// Auto-generated product data from image directory
const productData = [
  {
    category: "矩阵灯太空灯",
    subCategory: "四头灯太空灯",
    id: 1,
    name: "4头矩阵影视灯/太空灯",
    ModelName: "Prt-DT4-720W",
    image: [
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-1.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-10.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-2.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-3.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-4.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-5.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-6.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-7.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-8.png",
      "image/矩阵灯太空灯/四头灯太空灯/太空灯DT4-9.png"
    ],
    params: [
        { name: "产品型号", value: "Prt-DT4-720W" },
        { name: "额定功率", value: "720W" },
        { name: "模块数量", value: "4灯头" },
        { name: "色温", value: "2600K-6000K线性可调" },
        { name: "显色指数", value: "CRI≥96" },
        { name: "影视灯光一致性指数", value: "TLCI≥98" },
        { name: "颜色一致性指数", value: "CCI=0" },
        { name: "出光角度", value: "60°" },
        { name: "灯珠寿命", value: "约50000小时" },
        { name: "调光范围", value: "0～100% /万分级调光" },
        { name: "光学系统", value: "0～100%线性调光" },
        { name: "控制模式", value: "灯体/DMX512/无线DMX512" },
        { name: "信号通道数", value: "5CH～17CH" },
        { name: "信号连接", value: "DMX IN / DMX OUT" },
        { name: "数码显示", value: "LCD液晶屏显示" },
        { name: "分区控制", value: "四域控制" },
        { name: "散热方式", value: "主动散热" },
        { name: "外壳材质", value: "铝合金" },
        { name: "输入电压", value: "100V～240V AC/50～60Hz" },
        { name: "电源连接", value: "POWER IN" },
        { name: "防护等级", value: "IP23" },
        { name: "工作温度", value: "-20~50℃" },
        { name: "灯体重量", value: "18.75kg" },
        { name: "规格尺寸", value: "584mm×584mm×207mm" }
      ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 2,
    name: "电动铰链 - 2动作",
    ModelName: "DJL-2D（2m/3m/4m/5m）",
    image: [
      "image/控制与配件/恒力铰链吊杆/电动铰链2动作/1电动铰链DJL-EH-2D-2.jpg",
      "image/控制与配件/恒力铰链吊杆/电动铰链2动作/1电动铰链DJL-EH-2D-1.jpg"
    ],
    params: [
      { name: "输入电压", value: "AC220V 50~60Hz" },
      { name: "电源接口", value: "三芯 in/out" },
      { name: "提升电机功率", value: "60W" },
      { name: "设备自重", value: "12～15kg" },
      { name: "提升重量", value: "3～30kg" },
      { name: "提升速度", value: "6m/min" },
      { name: "控制协议", value: "专用控台+DMX512协议控制" },
      { name: "材质", value: "铝合金型材+优质冷轧钢承重结构" },
      { name: "地址码显示", value: "LED屏显示" },
      { name: "功能", value: "电动恒力铰链吊杆采用数字集成模块控制电机工作模式，可自由设定地址码，通过DMX远程控制灯光上下升降，带有限位系统定位准确，安全可靠。适用于中小型演播室、小型舞台、报告厅等吊挂灯具。" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 3,
    name: "万向滑车",
    ModelName: "Prt-HC08",
    image: [
      "image/控制与配件/恒力铰链吊杆/万向滑车/O1CN01CyUN8720KeK8KKDxW_!!2210064516831-0-cib.jpg",
      "image/控制与配件/恒力铰链吊杆/万向滑车/O1CN01oOuMbp20KeK57vmIZ_!!2210064516831-0-cib.jpg",
      "image/控制与配件/恒力铰链吊杆/万向滑车/WechatIMG361.jpg",
      "image/控制与配件/恒力铰链吊杆/万向滑车/万向滑车.jpg"
    ],
    params: [
      { name: "尺寸", value: "L100mm×W70mm×H90mm" },
      { name: "承重", value: "≥350KG" },
      { name: "颜色", value: "黑色，表面做黑色静电喷涂" },
      { name: "材质", value: "6063T6铝合金，经熔铸、挤压等工艺加工，结实耐用，承重力强" },
      { name: "滑轮", value: "八轮滚珠轴承体，滑动轻巧无噪音" },
      { name: "噪音", value: "静音设计" },
      { name: "旋转角度", value: "360°" },
      { name: "功能", value: "用于吊挂滑动轨道、让轨道实现前后、左右移用及各方向的转动" },
      { name: "适用范围", value: "电视台，学校，政企，融媒体中心灯光，中小型演播室灯光，演播厅灯光，访谈类演播室灯光、虚拟演播室灯光、全景演播室灯光，摄影棚灯光吊装" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 4,
    name: "保险绳",
    ModelName: "Prt-GS600",
    image: [
      "image/控制与配件/恒力铰链吊杆/保险绳/O1CN01hQph0Q20KeK9QVD0u_!!2210064516831-0-cib.jpg"
    ],
    params: [
      { name: "品名", value: "钢丝绳/灯具保险链" },
      { name: "材质", value: "3mm钢丝+包胶" },
      { name: "规格尺寸", value: "长度600mm×3mm直径，带安全弹簧锁扣：4MM+5MM扣件" },
      { name: "自重", value: "约0.06kg" },
      { name: "承重", value: "≥30kg" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 5,
    name: "吊灯轴",
    ModelName: "Prt-M6",
    image: [
      "image/控制与配件/恒力铰链吊杆/吊灯轴/O1CN01ZbDKFJ20KeK3Oubr3_!!2210064516831-0-cib.jpg"
    ],
    params: [
      { name: "材质", value: "钢制" },
      { name: "螺牙", value: "M6" },
      { name: "承重", value: "≥35kg" },
      { name: "功能", value: "用于灯具滑车与铰链和演播灯具的连接" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 6,
    name: "电动铰链 - 4动作",
    ModelName: "DJL-4D（2m/3m/4m/5m）",
    image: [
      "image/控制与配件/恒力铰链吊杆/电动铰链4动作/2电动铰链DJL-EH-4D-1.jpg",
      "image/控制与配件/恒力铰链吊杆/电动铰链4动作/2电动铰链DJL-EH-4D-2.jpg"
    ],
    params: [
      { name: "输入电压", value: "AC220V 50~60Hz" },
      { name: "电源接口", value: "三芯 in/out" },
      { name: "提升电机功率", value: "60W" },
      { name: "行走电机功率", value: "30W" },
      { name: "设备自重", value: "12～15kg" },
      { name: "提升重量", value: "3～30kg" },
      { name: "提升速度", value: "6m/min" },
      { name: "行走速度", value: "3m/min" },
      { name: "控制协议", value: "专用控台+DMX512协议控制" },
      { name: "材质", value: "铝合金型材+优质冷轧钢承重结构" },
      { name: "地址码显示", value: "LED屏显示" },
      { name: "功能", value: "电动恒力铰链吊杆采用数字集成模块控制电机工作模式，可自由设定地址码，通过DMX远程控制灯光上下升降，左右或是前后行走，带有限位系统定位准确，安全可靠。适用于中小型演播室、小型舞台、报告厅等吊挂灯具。" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 7,
    name: "恒力铰链",
    ModelName: "Prt-JL1.2",
    image: [
      "image/控制与配件/恒力铰链吊杆/恒力铰链/5恒力铰链-1.jpg",
      "image/控制与配件/恒力铰链吊杆/恒力铰链/5恒力铰链-2.jpeg"
    ],
    params: [
      { name: "规格", value: "1.2M/2.12KG，1.5M/2.56KG，2.0M/3.28KG，2.5M/3.8KG，3.0M/5.66KG" },
      { name: "承重范围", value: "≥15KG" },
      { name: "颜色", value: "黑色" },
      { name: "材质", value: "铝合金" },
      { name: "铰链自重", value: "1.2M/2.12KG，1.5M/2.56KG，2.0M/3.28KG，2.5M/3.8KG，4.0M/5.66KG" },
      { name: "结构特点", value: "磨擦片阻尼、钢丝绳与回力弹簧结构，灯具在吊杆伸缩范围内能停止在任何位置上，无上缩下伸现像，定位准确" },
      { name: "功能", value: "可使LED灯具上下移动升降,放置在一个合适的高度,定位稳定,满足舞台表演和演播厅灯光布置高标准要求" },
      { name: "适用场景", value: "中小型演播室，虚拟演播室，直播间，小型舞台等" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 8,
    name: "电动吊杆 - 2动作",
    ModelName: "DJL-2D（2m/3m/4m/5m）",
    image: [
      "image/控制与配件/恒力铰链吊杆/电动吊杆2动作/3电动吊杆DJL-EB-2D-1.jpg",
      "image/控制与配件/恒力铰链吊杆/电动吊杆2动作/3电动吊杆DJL-EB-2D-2.jpg"
    ],
    params: [
      { name: "输入电压", value: "AC220V 50~60Hz" },
      { name: "电源接口", value: "三芯 in/out" },
      { name: "提升电机功率", value: "60W" },
      { name: "设备自重", value: "12～15kg" },
      { name: "提升重量", value: "2～35kg" },
      { name: "提升速度", value: "6m/min" },
      { name: "控制协议", value: "专用控台+DMX512协议控制" },
      { name: "材质", value: "铝合金型材+优质冷轧钢承重结构" },
      { name: "地址码显示", value: "LED屏显示" },
      { name: "功能", value: "电动恒力铰链吊杆采用数字集成模块控制电机工作模式，可自由设定地址码，通过DMX远程控制灯光上下升降，带有限位系统定位准确，安全可靠。适用于中小型演播室、融媒体中心、小型舞台、报告厅等吊挂灯具。" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 9,
    name: "电动吊杆 - 4动作",
    ModelName: "DJL-4D（2m/3m/4m/5m）",
    image: [
      "image/控制与配件/恒力铰链吊杆/电动吊杆4动作/4电动吊杆DJL-EB-4D-1.jpg",
      "image/控制与配件/恒力铰链吊杆/电动吊杆4动作/4电动吊杆DJL-EB-4D-2.jpg"
    ],
    params: [
      { name: "输入电压", value: "AC220V 50~60Hz" },
      { name: "电源接口", value: "三芯 in/out" },
      { name: "提升电机功率", value: "60W" },
      { name: "行走电机功率", value: "30W" },
      { name: "设备自重", value: "12～15kg" },
      { name: "提升重量", value: "2～35kg" },
      { name: "提升速度", value: "6m/min" },
      { name: "行走速度", value: "3m/min" },
      { name: "控制协议", value: "专用控台+DMX512协议控制" },
      { name: "材质", value: "铝合金型材+优质冷轧钢承重结构" },
      { name: "地址码显示", value: "LED屏显示" },
      { name: "功能", value: "电动恒力铰链吊杆采用数字集成模块控制电机工作模式，可自由设定地址码，通过DMX远程控制灯光上下升降，左右或是前后行走，带有限位系统定位准确，安全可靠。适用于中小型演播室、融媒体中心、小型舞台、报告厅等吊挂灯具。" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 10,
    name: "轨道堵头",
    ModelName: "Prt-DT02",
    image: [
      "image/控制与配件/恒力铰链吊杆/轨道堵头/O1CN01G6MhBw20KeS8x5Dww_!!2210064516831-0-cib.jpg",
      "image/控制与配件/恒力铰链吊杆/轨道堵头/轨道堵头.jpeg"
    ],
    params: [
      { name: "规格", value: "87.5x66x24.3（mm）" },
      { name: "颜色", value: "白色" },
      { name: "材质", value: "ABS工程塑料，一次模压成型" },
      { name: "卡槽尺寸", value: "高81mm，宽61mm，槽宽4.5mm" },
      { name: "自重", value: "0.15KG" },
      { name: "功能", value: "阻止滑车脱轨，墙面不被破坏" },
      { name: "安装方式", value: "套装在铝合金轨道上，然后用1个螺丝固定，每根轨道配置2个轨道堵头" },
      { name: "适用范围", value: "电视台，学校，政企，融媒体中心灯光，中小型演播室灯光，演播厅灯光，访谈类演播室灯光、虚拟演播室灯光、全景演播室灯光，摄影棚灯光阻止滑车脱轨，轨道移动时撞到墙面，保护墙面" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 11,
    name: "轨道托板",
    ModelName: "没有参数！",
    image: [
      "image/控制与配件/恒力铰链吊杆/轨道托板/轨道托板1.jpg",
      "image/控制与配件/恒力铰链吊杆/轨道托板/轨道托板2.jpeg",
      "image/控制与配件/恒力铰链吊杆/轨道托板/16轨道托板-3.jpeg"
    ],
    params: [
      { name: "待填写", value: "000" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 12,
    name: "灯具滑车",
    ModelName: "Prt-HC04",
    image: [
      "image/控制与配件/恒力铰链吊杆/灯具滑车/灯具滑车1.jpg",
      "image/控制与配件/恒力铰链吊杆/灯具滑车/灯具滑车2.jpg",
      "image/控制与配件/恒力铰链吊杆/轨道灯具滑车/铝合金轨道+灯具滑车.jpg"
    ],
    params: [
      { name: "尺寸", value: "L100mm×W70mm×H50mm" },
      { name: "承重", value: "≥200KG" },
      { name: "颜色", value: "黑色，表面做黑色静电喷涂" },
      { name: "材质", value: "6063T6铝合金，经熔铸、挤压等工艺加工，结实耐用，承重力强" },
      { name: "滑轮", value: "四轮滚珠轴承体，滑动轻巧无噪音" },
      { name: "噪音", value: "静音设计" },
      { name: "运行", value: "水平移动" },
      { name: "功能", value: "用于吊挂灯具、让灯具在滑动轨道上实现水平移用" },
      { name: "适用范围", value: "电视台，学校，政企，融媒体中心灯光，中小型演播室灯光，演播厅灯光，访谈类演播室灯光、虚拟演播室灯光、全景演播室灯光，摄影棚灯光吊装" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 13,
    name: "轨道吊架",
    ModelName: "Prt-DJ09",
    image: [
      "image/控制与配件/恒力铰链吊杆/轨道吊架/12轨道吊架.jpg"
    ],
    params: [
      { name: "承重", value: "≥520kg" },
      { name: "规格", value: "底座长150mm×宽150mm、方管40mmX40mmX2.5mm" },
      { name: "可调范围", value: "0.9米、0.8米、0.7米、0.6米、0.5米" },
      { name: "外观", value: "静电喷涂工艺，由方形钢管和轨道压片焊接而成" },
      { name: "材质", value: "全金属" },
      { name: "功能", value: "固定轨吊架，现场无需电焊，是固定铝合金轨道的承重主梁，有固定式和可调式两种规格，结构经凑，通过膨胀螺丝固定于天花板，另一端用螺丝锁紧轨道压片固定轨道，可根据现场情况调节高度垂直拉伸使用，满足轨道不同高度安装需求" },
      { name: "适用范围", value: "电视台，学校，政企，融媒体中心灯光，中小型演播室灯光，演播厅灯光，访谈类演播室灯光、虚拟演播室灯光、全景演播室灯光，摄影棚灯光专用配件。" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 14,
    name: "灯具号码牌",
    ModelName: "Prt-HM02",
    image: [
      "image/控制与配件/恒力铰链吊杆/灯具号码牌/13灯具号码牌.jpg"
    ],
    params: [
      { name: "材质", value: "亚克力，聚甲基丙烯酸甲酯" },
      { name: "数字", value: "双面数字（可根据要求定制数字）" },
      { name: "尺寸", value: "110mm×170mm×2mm" },
      { name: "作用", value: "表示灯的序号或是地址码，用扎带固定在灯体上，方便远程调灯时辨别。" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 15,
    name: "轨道连接件",
    ModelName: "Prt-LJ300",
    image: [
      "image/控制与配件/恒力铰链吊杆/轨道连接件/14轨道连接件-1.jpg",
      "image/控制与配件/恒力铰链吊杆/轨道连接件/14轨道连接件-2.jpg"
    ],
    params: [
      { name: "尺寸", value: "L300mm×W60mm×H5mm" },
      { name: "外观", value: "黑色、静电喷涂工艺" },
      { name: "材质", value: "钢制" },
      { name: "重量", value: "约1.3Kg" }
    ],
    description: "轨道连接件用于两根工字轨道之间的连接，固定在两根工字轨道连接处的凹槽内，从而实现轨道无限延长，可根据要求定制轨道长度，适合用于较大跨度的摄影棚、演播室灯光布置。每个连接点左右各加装1个，2个为1套"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 16,
    name: "铝合金轨道",
    ModelName: "Prt-GD03/GD04",
    image: [
      "image/控制与配件/恒力铰链吊杆/铝合金轨道/铝合金轨道.jpg",
      "image/控制与配件/恒力铰链吊杆/铝合金轨道/铝合金轨道2.jpg",
      "image/控制与配件/恒力铰链吊杆/铝合金轨道/铝合金轨道+堵头.jpg",
      "image/控制与配件/恒力铰链吊杆/铝合金轨道/墙装铝合金轨道.jpeg"
    ],
    params: [
      { name: "规格", value: "L3000mm×W60mm×H80mm / L4000mm×W60mm×H80mm" },
      { name: "承重", value: "≥300KG" },
      { name: "颜色", value: "银色，表面做阳极氧化处理" },
      { name: "材质", value: "6063T6铝合金，经熔铸、挤压、氧化等工艺加工，柔韧性更强" },
      { name: "形状", value: "工字型" },
      { name: "弧形", value: "根据设计现场需求，可加工成需要的弧，可做成圆" },
      { name: "功能", value: "可吊挂滑动轨道、恒力铰链、万向滑车、灯具滑车、线缆滑车" },
      { name: "适用范围", value: "电视台，学校，政企，融媒体中心灯光，中小型演播室灯光，演播厅灯光，访谈类演播室灯光、虚拟演播室灯光、全景演播室灯光，摄影棚灯光吊装" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 17,
    name: "铰链头",
    image: [
      "image/控制与配件/恒力铰链吊杆/铰链头/铰链头.jpeg"
    ],
    params: [
      { name: "待填写", value: "000" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "演播室配件",
    id: 18,
    name: "DMX信号分线盒",
    ModelName: "FPQ-X05",
    image: [
      "image/控制与配件/演播室配件/DMX信号分配器/DMX信号分配器1.png",
      "image/控制与配件/演播室配件/DMX信号分配器/DMX信号分配器2.png",
      "image/控制与配件/演播室配件/DMX信号分配器/DMX信号分配器3.png"
    ],
    params: [
      { name: "输入电源", value: "220V/50Hz" },
      { name: "功能", value: "一路进五路出" },
      { name: "材料", value: "钢制，金属插座插头" },
      { name: "颜色", value: "黑色，输入、输出三芯卡农座" },
      { name: "配置", value: "一个信号分配器+6个金属三芯卡农座" },
      { name: "适用范围", value: "电视台，学校，政企，融媒体中心灯光，中小型演播室灯光，演播厅灯光，访谈类演播室灯光、虚拟演播室灯光、全景演播室灯光，摄影棚灯光专信号分配器" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "演播室配件",
    id: 19,
    name: "电源分线盒",
    ModelName: "FPQ-D05",
    image: [
      "image/控制与配件/演播室配件/电源分配器/电源分配器1.png",
      "image/控制与配件/演播室配件/电源分配器/电源分配器2.png",
      "image/控制与配件/演播室配件/电源分配器/电源分配器3.png",
      "image/控制与配件/演播室配件/电源分配器/电源分配器4.png",
      "image/控制与配件/演播室配件/电源分配器/电源分配器5.png",
      "image/控制与配件/演播室配件/电源分配器/电源分配器6.png"
    ],
    params: [
      { name: "最大负载", value: "3500W" },
      { name: "输入电源", value: "220V/50Hz" },
      { name: "功能", value: "一路进五路出" },
      { name: "材料", value: "钢制，插座插头材质为玻璃纤维" },
      { name: "颜色", value: "黑色，输入、输出航空自锁电源插座" },
      { name: "配置", value: "一个电源分线盒+6个蓝色航空自锁电源插头" },
      { name: "适用范围", value: "电视台，学校，政企，融媒体中心灯光，中小型演播室灯光，演播厅灯光，访谈类演播室灯光、虚拟演播室灯光、全景演播室灯光，摄影棚灯光专用电源分配器" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "电源箱",
    id: 20,
    name: "48路 电源直通柜",
    ModelName: "ZTX-GH48/4KW",
    image: [
      "image/控制与配件/电源箱/ZTG-GH484KW/ZTG-GH484KW直通柜-1.png",
      "image/控制与配件/电源箱/ZTG-GH484KW/ZTG-GH484KW直通柜-2.png",
      "image/控制与配件/电源箱/ZTG-GH484KW/ZTG-GH484KW直通柜-3.png"
    ],
    params: [
      { name: "总空开", value: "德力西250A总空开" },
      { name: "单路空开", value: "德力西20A独立空开" },
      { name: "供电", value: "三相五线制AC380±10%" },
      { name: "电源输入", value: "三相五线制200A犀牛插座" },
      { name: "输出电压", value: "220V10%50/60Hz" },
      { name: "电源输出", value: "48路40A胶木插座" },
      { name: "扩展接口", value: "2路防水五孔万用插座" },
      { name: "电压显示", value: "三相A、B、C独立液晶电流、电压表显示" },
      { name: "安装方式", value: "落地，可移动使用" },
      { name: "机柜大小", value: "12U标准机柜" },
      { name: "机箱材质", value: "采用精致耐用双层防震六角纹材质" },
      { name: "控制系统", value: "每路单独开关控制，具备过载，短路双重保护" },
      { name: "内部接线", value: "10平方主线+每路4平方国标线" },
      { name: "重量", value: "51kg" },
      { name: "尺寸", value: "715*625*765mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "电源箱",
    id: 21,
    name: "12路 电源直通箱",
    ModelName: "ZTX-GH12/4KW",
    image: [
      "image/控制与配件/电源箱/ZTX-GH124KW/ZTX-GH124KW-6直通箱.jpg",
      "image/控制与配件/电源箱/ZTX-GH124KW/ZTX-GH124KW-7直通箱.jpg",
      "image/控制与配件/电源箱/ZTX-GH124KW/ZTX-GH124KW直通箱-2.png",
      "image/控制与配件/电源箱/ZTX-GH124KW/ZTX-GH124KW直通箱-3.png",
      "image/控制与配件/电源箱/ZTX-GH124KW/ZTX-GH124KW直通箱-4.png",
      "image/控制与配件/电源箱/ZTX-GH124KW/ZTX-GH124KW直通箱-5.png",
      "image/控制与配件/电源箱/ZTX-GH124KW/ZTX-GH124KW路通箱-1.png"
    ],
    params: [
      { name: "额定功率", value: "12路×4KW" },
      { name: "接线方式", value: "三相五线制" },
      { name: "输入电压", value: "AC380V±10％" },
      { name: "频率", value: "50Hz±5％" },
      { name: "控制方式", value: "12路过载与短路双重保护高分断空气独立开关" },
      { name: "电源指示", value: "三相A.B.C电压数码显示/工作指示灯" },
      { name: "电源插座", value: "配备1个五孔插座+3个三孔插座" },
      { name: "产品尺寸", value: "480mm×270mm×150mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "电源箱",
    id: 22,
    name: "24路 电源直通箱",
    ModelName: "ZTX-GH24/4KW",
    image: [
      "image/控制与配件/电源箱/ZTX-GH244KW/ZTX-GH244KW-1直通箱.png",
      "image/控制与配件/电源箱/ZTX-GH244KW/ZTX-GH244KW-2直通箱.png",
      "image/控制与配件/电源箱/ZTX-GH244KW/ZTX-GH244KW-3直通箱.png",
      "image/控制与配件/电源箱/ZTX-GH244KW/ZTX-GH244KW-4直通箱.png",
      "image/控制与配件/电源箱/ZTX-GH244KW/ZTX-GH244KW-5.jpg",
      "image/控制与配件/电源箱/ZTX-GH244KW/ZTX-GH244KW-6.jpg"
    ],
    params: [
      { name: "额定功率", value: "24路×4KW" },
      { name: "接线方式", value: "三相五线制" },
      { name: "输入电压", value: "AC380V±10％" },
      { name: "频率", value: "50Hz±5％" },
      { name: "控制方式", value: "一个总开+24路过载与短路双重保护高分断空气独立开关" },
      { name: "电源指示", value: "三相A.B.C电压数码显示/工作指示灯" },
      { name: "电源插座", value: "配备3个三孔插座" },
      { name: "产品尺寸", value: "480mm×270mm×150mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "调光台信号放大器",
    id: 23,
    name: "全隔离信号放大器",
    ModelName: "FDQ-H08",
    image: [
      "image/控制与配件/调光台信号放大器/FDQ-H08信号放大器/FDQ-H08信号放大器-1.png",
      "image/控制与配件/调光台信号放大器/FDQ-H08信号放大器/FDQ-H08信号放大器-2.png",
      "image/控制与配件/调光台信号放大器/FDQ-H08信号放大器/FDQ-H08信号放大器-3.jpg"
    ],
    params: [
      { name: "控制协议", value: "DMX512/1990" },
      { name: "额定功率", value: "15W" },
      { name: "信号输入/出", value: "1路输入，1路直通输出" },
      { name: "输出接口", value: "8路光电隔离信号分配输出" },
      { name: "信号接口类型", value: "XLR-3Male，XLR-D3Female" },
      { name: "末端电阻", value: "120Ω" },
      { name: "输入电压", value: "90V～240V/50～60Hz" },
      { name: "机身重量", value: "2.0kg" },
      { name: "包装尺寸", value: "500mm×190mm×10mm" },
      { name: "特点", value: "带信号修正、双模电源、隔离模块自带120Ω末端电阻，内置高性能绿色开关电源，具有极低电源谐波失真和极宽电压适用范围。2路带隔离的独立输出驱动端口，具有抗1500VDC电气冲击能力，每路具有独立放大器及信号指示" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "调光台信号放大器",
    id: 24,
    name: "1024电脑调光台",
    ModelName: "KK-1024",
    image: [
      "image/控制与配件/调光台信号放大器/KK-1024控台/KK-1024控台.png"
    ],
    params: [
      { name: "控制协议", value: "DMX512/1990标准，最大1024个DMX控制通道，两路光电隔离信号输出" },
      { name: "最大控制", value: "96台电脑灯或96路调光" },
      { name: "灯库", value: "使用珍珠灯库（R20格式灯库），且控台上可自行编写灯库" },
      { name: "显示屏", value: "带背光的LCD显示屏，首创的中英文显示可切换界面。面板中英文可选" },
      { name: "图形轨迹发生器", value: "内置图形轨迹发生器，有135个内置图形，方便用户对电脑灯进行图形轨迹控制，如画圆、螺旋、彩虹、追逐等多种效果" },
      { name: "图形参数", value: "图形参数（如：振幅、速度、间隔、波浪、方向）均可独立设置，更方便快捷的做出想要的造型和场景" },
      { name: "图形数量", value: "每个场景可保存图形数量5个；同时可运行图形数量10个" },
      { name: "素材储存", value: "可储存60个素材" },
      { name: "独享素材", value: "支持独享素材" },
      { name: "重演场景", value: "可储存60个重演场景，用于储存多步场景和单步场景。每个多步场景最多可储存600个单步" },
      { name: "重演场景输出", value: "可同时输出和运行10个重演场景" },
      { name: "集控推杆", value: "带10根集控推杆。按键点控和推杆集控兼容" },
      { name: "功能支持", value: "支持重新配节地址码、垂直水平交换、通道输出反向等功能" },
      { name: "数据记忆", value: "关机或者突发断电等情况数据可记忆保持" },
      { name: "U盘备份", value: "U盘可备份控台数据，并支持重新导入到控台使用，同型号控台数据可共享" },
      { name: "预置推杆", value: "预置推杆可控制电脑灯的属性，属性控制更方便快捷" },
      { name: "立即黑场", value: "支持立即黑场" },
      { name: "工作灯", value: "专业鹅颈工作灯，适合室内外演出使用。（选配）" },
      { name: "额定功率", value: "15W" },
      { name: "电源", value: "AC 100 -240V / 50-60Hz" },
      { name: "净重", value: "7.3kg" },
      { name: "产品尺寸", value: "485*400*105" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "调光台信号放大器",
    id: 25,
    name: "数字调光台",
    ModelName: "KT-2600",
    image: [
      "image/控制与配件/调光台信号放大器/KT-2600控台/KT-2600.jpg",
      "image/控制与配件/调光台信号放大器/KT-2600控台/KT-2600.png"
    ],
    params: [
      { name: "控制协议", value: "DMX512/1990标准" },
      { name: "通道数量", value: "最大256个DMX控制通道" },
      { name: "推杆数量", value: "16 个推杆(CH1-16)" },
      { name: "数字键", value: "16个（1-16）用于选择走灯程序、选择电脑灯" },
      { name: "可控制灯具", value: "可控制 16 组电脑灯具" },
      { name: "信号输入/出", value: "1路输入，1路直通输出，4路光电隔离增强信号同步输出" },
      { name: "信号接口", value: "XLR-3 Male Connector" },
      { name: "BANK/SCENES", value: "可编程程序，具备场景控制功能" },
      { name: "显示屏", value: "LCD 液晶显示屏" },
      { name: "暗场功能", value: "黑场键可实现所有通道输出零，达到黑场效果" },
      { name: "渐变调节", value: "调节两步程序之间的渐变时间" },
      { name: "速度调节", value: "调节程序播放时每一步的停留时间" },
      { name: "程序播放功能", value: "有" },
      { name: "手动提灯功能", value: "有" },
      { name: "声控功能", value: "在播放程序时，可以通过声控键控制程序的运行" },
      { name: "工作环境", value: "适合在无腐蚀性、可燃气体、可自然通风的场所使用" },
      { name: "颜色", value: "黑色+橙色" },
      { name: "电压", value: "100V～220V/50~60HZ" },
      { name: "电源输入", value: "16A 航空电源输入" },
      { name: "重量", value: "3.54kg" },
      { name: "外形尺寸", value: "482*270*50mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "调光台信号放大器",
    id: 26,
    name: "数字调光台",
    ModelName: "KT-2601",
    image: [
      "image/控制与配件/调光台信号放大器/KT-2601控台/KT-2601-2.jpg",
      "image/控制与配件/调光台信号放大器/KT-2601控台/KT-2601.jpg"
    ],
    params: [
      { name: "控制协议", value: "DMX512/1990标准" },
      { name: "通道数量", value: "最大256个DMX控制通道" },
      { name: "推杆数量", value: "16 个推杆(CH1-16)" },
      { name: "数字键", value: "16个（1-16）用于选择走灯程序、选择电脑灯" },
      { name: "可控制灯具", value: "可控制 16 组电脑灯具" },
      { name: "信号输入/出", value: "1路输入，1路直通输出" },
      { name: "信号接口", value: "XLR-3 Male Connector" },
      { name: "BANK/SCENES", value: "可编程程序，具备场景控制功能" },
      { name: "显示屏", value: "LCD 液晶显示屏" },
      { name: "暗场功能", value: "黑场键可实现所有通道输出零，达到黑场效果" },
      { name: "渐变调节", value: "调节两步程序之间的渐变时间" },
      { name: "速度调节", value: "调节程序播放时每一步的停留时间" },
      { name: "程序播放功能", value: "有" },
      { name: "手动提灯功能", value: "有" },
      { name: "声控功能", value: "在播放程序时，可以通过声控键控制程序的运行" },
      { name: "工作环境", value: "适合在无腐蚀性、可燃气体、可自然通风的场所使用" },
      { name: "颜色", value: "黑色+橙色" },
      { name: "电压", value: "100V～220V/50~60HZ" },
      { name: "电源输入", value: "16A 航空电源输入" },
      { name: "重量", value: "3.54kg" },
      { name: "外形尺寸", value: "482*270*50mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "调光台信号放大器",
    id: 27,
    name: "24路 智能调光台",
    ModelName: "SC-K240",
    image: [
      "image/控制与配件/调光台信号放大器/SC-K240控台/SC-K240.jpg",
      "image/控制与配件/调光台信号放大器/SC-K240控台/SC-K240.png"
    ],
    params: [
      { name: "控制协议", value: "DMX512/1990标准" },
      { name: "通道数量", value: "24个DMX通道" },
      { name: "推杆数量", value: "24 个灯控推杆(CH1-16)+ 6个集控推杆" },
      { name: "Flash 按键", value: "24个（1-24）点控按键+6个集控按键" },
      { name: "信号输入/出", value: "2路电气隔离输出" },
      { name: "Fine/Fine+ 按键", value: "对当前调光通道进行微调" },
      { name: "DIAL/ENTER 数码轮", value: "选择或查看项目，确认存储集控" },
      { name: "Master 总控推杆", value: "总调节通道亮度值" },
      { name: "集控推杆", value: "控制集控的亮度值" },
      { name: "集控按键", value: "执行集控点动输出" },
      { name: "显示屏", value: "LCD 液晶显示屏" },
      { name: "LAMP ONLY", value: "LED 工作灯插座" },
      { name: "RS232 接口", value: "连接中控实现远程调用集控" },
      { name: "SLAVE 接口", value: "用于主机与从机连接，扩展通道，可扩展为4台96个通道" },
      { name: "LINK TO MASTER 接口", value: "当本机作为从机时，连接到主机" },
      { name: "中控远程控制", value: "波特率 9600，RS232接口连接中控系统" },
      { name: "主从机配置", value: "使用 RJ45 网线连接 LINK TO MASTER 接口和 SLAVE接口" },
      { name: "信号接口", value: "XLR-D3F" },
      { name: "电源输入", value: "AC88~256V 50/60HZ" },
      { name: "电源输出", value: "AC88~256V 50/60HZ" },
      { name: "净重", value: "2.65kg" },
      { name: "尺寸", value: "482x265x75mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "调光台信号放大器",
    id: 28,
    name: "48路 智能调光台",
    ModelName: "SC-K480",
    image: [
      "image/控制与配件/调光台信号放大器/SC-K480控台/SC-K480.jpg",
      "image/控制与配件/调光台信号放大器/SC-K480控台/SC-K480.png"
    ],
    params: [
      { name: "控制协议", value: "DMX512/1990标准" },
      { name: "通道数量", value: "48个DMX通道" },
      { name: "推杆数量", value: "24 个灯控推杆(CH1-24)可翻2页+ 6个集控推杆" },
      { name: "Flash 按键", value: "24个（1-24）点控按键+6个集控按键" },
      { name: "信号输入/出", value: "2路电气隔离输出" },
      { name: "Fine/Fine+ 按键", value: "对当前调光通道进行微调" },
      { name: "DIAL/ENTER 数码轮", value: "选择或查看项目，确认存储集控" },
      { name: "Master 总控推杆", value: "总调节通道亮度值" },
      { name: "集控推杆", value: "控制集控的亮度值" },
      { name: "集控按键", value: "执行集控点动输出" },
      { name: "显示屏", value: "LCD 液晶显示屏" },
      { name: "LAMP ONLY", value: "LED 工作灯插座" },
      { name: "RS232 接口", value: "连接中控实现远程调用集控" },
      { name: "SLAVE 接口", value: "用于主机与从机连接，扩展通道，可扩展为4台192个通道" },
      { name: "LINK TO MASTER 接口", value: "当本机作为从机时，连接到主机" },
      { name: "中控远程控制", value: "波特率 9600，RS232接口连接中控系统" },
      { name: "主从机配置", value: "使用 RJ45 网线连接 LINK TO MASTER 接口和 SLAVE接口" },
      { name: "信号接口", value: "XLR-D3F" },
      { name: "电源输入", value: "AC88~256V 50/60HZ" },
      { name: "电源输出", value: "AC88~256V 50/60HZ" },
      { name: "净重", value: "2.65kg" },
      { name: "尺寸", value: "482x265x75mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "调光台信号放大器",
    id: 29,
    name: "96路 智能调光台",
    ModelName: "SC-K960",
    image: [
      "image/控制与配件/调光台信号放大器/SC-K960控台/SC-K960.jpg",
      "image/控制与配件/调光台信号放大器/SC-K960控台/SC-K960.png"
    ],
    params: [
      { name: "控制协议", value: "DMX512/1990标准" },
      { name: "通道数量", value: "96个DMX通道" },
      { name: "推杆数量", value: "48 个灯控推杆(CH1-48)可翻2页+ 12个集控推杆" },
      { name: "Flash 按键", value: "48个（1-48）点控按键+12个集控按键" },
      { name: "信号输入/出", value: "2路电气隔离输出" },
      { name: "Fine/Fine+ 按键", value: "对当前调光通道进行微调" },
      { name: "DIAL/ENTER 数码轮", value: "选择或查看项目，确认存储集控" },
      { name: "Master 总控推杆", value: "总调节通道亮度值" },
      { name: "集控推杆", value: "控制集控的亮度值" },
      { name: "集控按键", value: "执行集控点动输出" },
      { name: "显示屏", value: "LCD 液晶显示屏" },
      { name: "LAMP ONLY", value: "LED 工作灯插座" },
      { name: "RS232 接口", value: "连接中控实现远程调用集控" },
      { name: "SLAVE 接口", value: "用于主机与从机连接，扩展通道，可扩展为4台384个通道" },
      { name: "LINK TO MASTER 接口", value: "当本机作为从机时，连接到主机" },
      { name: "中控远程控制", value: "波特率 9600，RS232接口连接中控系统" },
      { name: "主从机配置", value: "使用 RJ45 网线连接 LINK TO MASTER 接口和 SLAVE接口" },
      { name: "信号接口", value: "XLR-D3F" },
      { name: "电源输入", value: "AC88~256V 50/60HZ" },
      { name: "电源输出", value: "AC88~256V 50/60HZ" },
      { name: "净重", value: "7.3kg" },
      { name: "尺寸", value: "498x420x115mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "调光台信号放大器",
    id: 30,
    name: "会议室墙面嵌入式触摸调光台",
    ModelName: "ZK-606",
    image: [
      "image/控制与配件/调光台信号放大器/ZK-606墙面嵌入式控制台/墙面嵌入式触摸控制台-1.jpg",
      "image/控制与配件/调光台信号放大器/ZK-606墙面嵌入式控制台/墙面嵌入式触摸控制台-2.jpg",
      "image/控制与配件/调光台信号放大器/ZK-606墙面嵌入式控制台/墙面嵌入式触摸控制台-3.jpg",
      "image/控制与配件/调光台信号放大器/ZK-606墙面嵌入式控制台/墙面嵌入式触摸控制台-4.png",
      "image/控制与配件/调光台信号放大器/ZK-606墙面嵌入式控制台/墙面嵌入式触摸控制台-5.png"
    ],
    params: [
      { name: "额定功率", value: "8W" },
      { name: "屏幕尺寸", value: "4寸液晶触摸屏" },
      { name: "屏幕分辨率", value: "480×480ppi" },
      { name: "集控场景数", value: "5个" },
      { name: "控制通道", value: "≥24个通道(CH1-24)" },
      { name: "信号输出", value: "DMX512" },
      { name: "菜单文字", value: "中文/英文" },
      { name: "控台模式", value: "支持CH1-24通道0～255级进行控制" },
      { name: "灯控模式", value: "支持各灯位的亮度、色温、角度分别独立控制" },
      { name: "场景模式", value: "支持5组场景光效编程并进行保存，使用时一键切换场景光效模式" },
      { name: "参数设置", value: "可对地址码进行设置，控台屏幕亮度调节等" },
      { name: "机身颜色", value: "黑色" },
      { name: "输入电压", value: "100V～240V/50~60HZ" },
      { name: "外型尺寸", value: "86mm×86mm×45mm,可装入普通86型盒中" }
    ],
    description: "描述待填写"
  },
  {
    id: 31,
  },
  {
    category: "演播室灯光",
    subCategory: "平板柔光灯",
    id: 32,
    name: "SD系列 演播室平板柔光灯",
    ModelName: "LP-SD120D /SD-120Bi",
    image: [
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-1.png",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-10.jpg",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-11.jpg",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-12.jpg",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-2.png",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-3.png",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-4.png",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-5.jpg",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-6.png",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-7.png",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-8.png",
      "image/演播室灯光/平板柔光灯/LP-SD120Bi/LP-SD120 Bi-9.png"
    ],
    params: [
      { name: "最大功率", value: "120W" },
      { name: "LED光源", value: "1360颗（WW暖白+CW冷白灯珠)" },
      { name: "灯光照度", value: "3339Lux@1m/5600K 120°；3386Lux@1m/3200K 120°" },
      { name: "光束角度", value: "120°" },
      { name: "色温范围", value: "5600K/2700K～6500K可选" },
      { name: "显色指数", value: "Ra≥97" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "颜色质量", value: "CQS≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "控制模块", value: "DMX512信号/演示/手动" },
      { name: "信号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "16bit" },
      { name: "通道模式", value: "3CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "2个旋钮控制/DMX512控制" },
      { name: "供电方式", value: "AC 100～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN / POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "无风机自然散热" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约5.5 kg" },
      { name: "体积", value: "620mm×372mm×118mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "演播室灯光",
    subCategory: "平板柔光灯",
    id: 33,
    name: "SD系列 演播室平板柔光灯",
    ModelName: "LP-SD160D /SD-160Bi",
    image: [
      "image/演播室灯光/平板柔光灯/LP-SD160Bi/LP-SD160 Bi-1.png",
      "image/演播室灯光/平板柔光灯/LP-SD160Bi/LP-SD160 Bi-2.png",
      "image/演播室灯光/平板柔光灯/LP-SD160Bi/LP-SD160 Bi-3.png",
      "image/演播室灯光/平板柔光灯/LP-SD160Bi/LP-SD160 Bi-4.png",
      "image/演播室灯光/平板柔光灯/LP-SD160Bi/LP-SD160 Bi-5.png",
      "image/演播室灯光/平板柔光灯/LP-SD160Bi/LP-SD160 Bi-6.png",
      "image/演播室灯光/平板柔光灯/LP-SD160Bi/LP-SD160 Bi-7.png",
      "image/演播室灯光/平板柔光灯/LP-SD160Bi/LP-SD160 Bi-8.png"
    ],
    params: [
      { name: "最大功率", value: "160W" },
      { name: "LED光源", value: "1360颗（WW暖白+CW冷白灯珠)" },
      { name: "灯光照度", value: "3799Lux@1m/5600K 120°；3615Lux@1m/3200K 120°" },
      { name: "光束角度", value: "120°" },
      { name: "色温范围", value: "3200K～5600K无级可调色温" },
      { name: "显色指数", value: "Ra≥97" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "颜色质量", value: "CQS≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "控制模块", value: "DMX512信号/演示/手动" },
      { name: "信号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "16bit" },
      { name: "通道模式", value: "3CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "2个旋钮控制/DMX512控制" },
      { name: "供电方式", value: "AC 100～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN / POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "无风机自然散热" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约5.5 kg" },
      { name: "体积", value: "620mm×372mm×118mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "演播室灯光",
    subCategory: "平板柔光灯",
    id: 34,
    name: "SD系列 演播室平板柔光灯",
    ModelName: "LP-SD220D /SD-220Bi",
    image: [
      "image/演播室灯光/平板柔光灯/LP-SD220Bi/LP-SD220 Bi-1.png",
      "image/演播室灯光/平板柔光灯/LP-SD220Bi/LP-SD220 Bi-2.png",
      "image/演播室灯光/平板柔光灯/LP-SD220Bi/LP-SD220 Bi-3.png",
      "image/演播室灯光/平板柔光灯/LP-SD220Bi/LP-SD220 Bi-4.png",
      "image/演播室灯光/平板柔光灯/LP-SD220Bi/LP-SD220 Bi-5.png",
      "image/演播室灯光/平板柔光灯/LP-SD220Bi/LP-SD220 Bi-6.png",
      "image/演播室灯光/平板柔光灯/LP-SD220Bi/LP-SD220 Bi-7.png"
    ],
    params: [
      { name: "最大功率", value: "200W" },
      { name: "LED光源", value: "WW(220W)、CW(220W)" },
      { name: "灯光照度", value: "1972Lux@2m/5600K 110°；1920Lux@2m/3200K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "5600K/3200K～5600K可选" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 97" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "20KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512信号/RDM" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "通道模式", value: "3CH /7CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮控制/DMX512控制" },
      { name: "供电方式", value: "AC 100～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN / POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "自然散热" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约13.2 kg" },
      { name: "体积", value: "675mm×423mm×155mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "演播室灯光",
    subCategory: "平板柔光灯",
    id: 35,
    name: "SF系列 演播室平板柔光灯",
    ModelName: "LP-SF150D Pro/SF-150Bi Pro",
    image: [
      "image/演播室灯光/平板柔光灯/LP-SF150 Pro/LP-SF150D Pro-1.png",
      "image/演播室灯光/平板柔光灯/LP-SF150 Pro/LP-SF150D Pro-2.png",
      "image/演播室灯光/平板柔光灯/LP-SF150 Pro/LP-SF150D Pro-3.png",
      "image/演播室灯光/平板柔光灯/LP-SF150 Pro/LP-SF150D Pro-4.png"
    ],
    params: [
      { name: "额定功率", value: "≥150W" },
      { name: "灯珠数量", value: "600颗高亮LED灯珠" },
      { name: "显色指数", value: "Ra≥97" },
      { name: "影视灯光一致性指数", value: "TLCI≥98" },
      { name: "标准色温", value: "5600K/3200K/3200K～5600K可选" },
      { name: "灯珠寿命", value: "约50000小时" },
      { name: "调光范围", value: "0～100% /千分级调光" },
      { name: "光学系统", value: "100%线性调光，无频闪，无噪音" },
      { name: "光束角度", value: "120°" },
      { name: "外壳材质", value: "铝合金" },
      { name: "冷却系统", value: "无风扇自然风冷散热" },
      { name: "智能温控", value: "温度显示，温度预警" },
      { name: "操作显示", value: "LCD液晶屏显示" },
      { name: "控制方式", value: "手动按键＋旋钮调光、DMX控制，2.4G无线遥" },
      { name: "DMX512信号保持", value: "丢失信号记忆功能，预防直播事故" },
      { name: "通道模式", value: "1CH/2CH" },
      { name: "信号连接", value: "DMX IN / DMX OUT" },
      { name: "电源插座", value: "POWER IN/POWER OUT" },
      { name: "输入电压", value: "AC110～240V/50～60Hz" },
      { name: "工作温度", value: "-20~50℃" },
      { name: "灯体重量", value: "5.25kg" },
      { name: "规格尺寸", value: "625mm×356mm×120mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "演播室灯光",
    subCategory: "平板柔光灯",
    id: 36,
    name: "SF系列 演播室平板柔光灯",
    ModelName: "LP-SF200D Pro/SF-200Bi Pro",
    image: [
      "image/演播室灯光/平板柔光灯/LP-SF200 Pro/LP-SF200 Pro-1.png",
      "image/演播室灯光/平板柔光灯/LP-SF200 Pro/LP-SF200 Pro-2.png",
      "image/演播室灯光/平板柔光灯/LP-SF200 Pro/LP-SF200 Pro-3.png",
      "image/演播室灯光/平板柔光灯/LP-SF200 Pro/LP-SF200 Pro-4.png",
      "image/演播室灯光/平板柔光灯/LP-SF200 Pro/LP-SF200 Pro-5.png",
      "image/演播室灯光/平板柔光灯/LP-SF200 Pro/LP-SF200 Pro-6.png"
    ],
    params: [
      { name: "额定功率", value: "≥200W" },
      { name: "灯珠数量", value: "1152颗高亮LED灯珠" },
      { name: "显色指数", value: "Ra≥97" },
      { name: "影视灯光一致性指数", value: "TLCI≥98" },
      { name: "标准色温", value: "5600K/3200K/3200K～5600K可选" },
      { name: "灯珠寿命", value: "约50000小时" },
      { name: "调光范围", value: "0～100% /千分级调光" },
      { name: "光学系统", value: "100%线性调光，无频闪，无噪音" },
      { name: "光束角度", value: "120°" },
      { name: "外壳材质", value: "铝合金" },
      { name: "冷却系统", value: "无风扇自然风冷散热" },
      { name: "显 示 屏", value: "LCD液晶屏显示" },
      { name: "控制协议", value: "旋钮调光、DMX512控光协议" },
      { name: "通道模式", value: "1CH/2CH" },
      { name: "信号连接", value: "DMX IN / DMX OUT" },
      { name: "电源插座", value: "POWER IN/POWER OUT" },
      { name: "输入电压", value: "AC110～240V/50～60Hz" },
      { name: "工作温度", value: "-20~50℃" },
      { name: "灯体重量", value: "5.2kg" },
      { name: "规格尺寸", value: "665mm×371mm×100mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "演播室灯光",
    subCategory: "影视聚光灯",
    id: 37,
    name: "G系列 演播室聚光灯",
    ModelName: "SP-G100 Pro",
    image: [
      "image/演播室灯光/影视聚光灯/SP-G100Pro/SP-G100 Pro-1.png",
      "image/演播室灯光/影视聚光灯/SP-G100Pro/SP-G100 Pro-2.png",
      "image/演播室灯光/影视聚光灯/SP-G100Pro/SP-G100 Pro-3.png",
      "image/演播室灯光/影视聚光灯/SP-G100Pro/SP-G100 Pro-4.png",
      "image/演播室灯光/影视聚光灯/SP-G100Pro/SP-G100 Pro-5.png"
    ],
    params: [
      { name: "额定功率", value: "≥100W" },
      { name: "光 源", value: "采用单颗COB 100W" },
      { name: "显色指数", value: "CRI≥95" },
      { name: "影视照明一致性指数", value: "TLCI≥ 97" },
      { name: "标准色温", value: "5600K±150" },
      { name: "灯珠寿命", value: "约50000小时" },
      { name: "调光功能", value: "0-100% 线性电子调光" },
      { name: "操作显示", value: "LCD液晶屏显示" },
      { name: "透镜尺寸", value: "130mm菲涅尔透镜" },
      { name: "出光角度", value: "25-60°" },
      { name: "调焦方式", value: "手动调焦" },
      { name: "散热方式", value: "无风机自然风冷散热" },
      { name: "控制方式", value: "DMX512控光协议+面板按键+旋钮" },
      { name: "通道模式", value: "单色温1个通道" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "额定电压", value: "AC100V-240V/50-60HZ" },
      { name: "电源连接", value: "POWER IN / POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体净重", value: "5.0kg" },
      { name: "规格尺寸", value: "350mm×305mm×310mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "演播室灯光",
    subCategory: "影视聚光灯",
    id: 38,
    name: "G系列 演播室聚光灯",
    ModelName: "SP-G120 Pro",
    image: [
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-120 Pro-1.png",
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-120 Pro-2.png",
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-120 Pro-3.png",
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-120 Pro-4.png",
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-120 Pro-6.png",
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-G120Pro-5.png",
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-G120Pro-7.jpg",
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-G120Pro-8.jpg",
      "image/演播室灯光/影视聚光灯/SP-G120Pro/SP-G120Pro-9.jpg"
    ],
    params: [
      { name: "额定功率", value: "≥120W" },
      { name: "光 源", value: "采用单颗COB LED发光体" },
      { name: "显色指数", value: "Ra≥97" },
      { name: "标准色温", value: "5600K±150" },
      { name: "灯珠寿命", value: "约50000小时" },
      { name: "调光功能", value: "0-100% 线性电子调光" },
      { name: "透镜尺寸", value: "180mm菲涅尔透镜" },
      { name: "出光角度", value: "25-60°" },
      { name: "调焦方式", value: "手动调焦(支持前后操作调焦）" },
      { name: "操作显示", value: "液晶屏显示地址码和相对照度、自带温度显示功能" },
      { name: "散热方式", value: "静音/自然散热" },
      { name: "控制协议", value: "DMX512控光协议" },
      { name: "控制方式", value: "DMX512/旋钮控制/按键控制" },
      { name: "通道模式", value: "1CH" },
      { name: "信号接口", value: "DMX IN / DMX OUT" },
      { name: "快捷控制", value: "可一键0%/50%/100%亮度进行快速切换" },
      { name: "USB接口", value: "2个USB电源输出接口" },
      { name: "额定电压", value: "AC100V-240V/50-60HZ" },
      { name: "电源接口", value: "POWER IN / POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体净重", value: "7.3kg" },
      { name: "规格尺寸", value: "410mm×380mm×365mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "DBi系列聚光灯",
    id: 39,
    name: "S系列 双色温影视柔光灯",
    ModelName: "Lightpanel S120 Bi",
    image: [
      "image/专业影视灯光/DBi系列聚光灯/S120 Bi/Lightpanel S120 Bi-1.png",
      "image/专业影视灯光/DBi系列聚光灯/S120 Bi/Lightpanel S120 Bi-2.png",
      "image/专业影视灯光/DBi系列聚光灯/S120 Bi/Lightpanel S120 Bi-3.png",
      "image/专业影视灯光/DBi系列聚光灯/S120 Bi/Lightpanel S120 Bi-4.png"
    ],
    params: [
      { name: "最大功率", value: "650W" },
      { name: "LED光源", value: "WW(650W)、CW(650W)" },
      { name: "灯光照度", value: "19590Lux@1m/5600K 110°；6200Lux@2m/5600K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "2700K～6500K" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "21.3KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/LumenRadio CRMX" },
      { name: "信号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "通道模式", value: "3CH/7CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz；DC 48V" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约18.5 kg" },
      { name: "体积", value: "1316mm×382mm×191mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "DBi系列聚光灯",
    id: 40,
    name: "S系列 双色温影视柔光灯",
    ModelName: "Lightpanel S30 Bi",
    image: [
      "image/专业影视灯光/DBi系列聚光灯/S30 Bi/Lightpanel S30 Bi-1.png",
      "image/专业影视灯光/DBi系列聚光灯/S30 Bi/Lightpanel S30 Bi-2.png",
      "image/专业影视灯光/DBi系列聚光灯/S30 Bi/Lightpanel S30 Bi-3.png",
      "image/专业影视灯光/DBi系列聚光灯/S30 Bi/Lightpanel S30 Bi-4.png",
      "image/专业影视灯光/DBi系列聚光灯/S30 Bi/Lightpanel S30 Bi-5.png",
      "image/专业影视灯光/DBi系列聚光灯/S30 Bi/Lightpanel S30 Bi-6.png"
    ],
    params: [
      { name: "最大功率", value: "200W" },
      { name: "LED光源", value: "WW(200W)、CW(200W)" },
      { name: "灯光照度", value: "1956Lux@2m/5600K 110°；1724Lux@2m/3200K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "2700K～6500K" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "21.3KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/LumenRadio CRMX" },
      { name: "信号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "通道模式", value: "3CH/7CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz；DC 48V" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约7.0 kg" },
      { name: "体积", value: "449mm×382mm×191mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "DBi系列聚光灯",
    id: 41,
    name: "S系列 双色温影视柔光灯",
    ModelName: "Lightpanel S60 Bi",
    image: [
      "image/专业影视灯光/DBi系列聚光灯/S60 Bi/Lightpanel S60 Bi-1.png",
      "image/专业影视灯光/DBi系列聚光灯/S60 Bi/Lightpanel S60 Bi-2.png",
      "image/专业影视灯光/DBi系列聚光灯/S60 Bi/Lightpanel S60 Bi-3.png",
      "image/专业影视灯光/DBi系列聚光灯/S60 Bi/Lightpanel S60 Bi-4.png",
      "image/专业影视灯光/DBi系列聚光灯/S60 Bi/Lightpanel S60 Bi-5.png",
      "image/专业影视灯光/DBi系列聚光灯/S60 Bi/Lightpanel S60 Bi-6.png",
      "image/专业影视灯光/DBi系列聚光灯/S60 Bi/Lightpanel S60 Bi-8.png"
    ],
    params: [
      { name: "最大功率", value: "350W" },
      { name: "LED光源", value: "WW(350W)、CW(350W)" },
      { name: "灯光照度", value: "6064Lux@2m/5600K 110°；5460Lux@2m/3200K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "2700K～6500K" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "21.3KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/LumenRadio CRMX" },
      { name: "信号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "通道模式", value: "3CH/7CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz；DC 48V" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约11.8 kg" },
      { name: "体积", value: "737mm×382mm×191mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "P系列全彩像素影视灯",
    id: 42,
    name: "P系列 双色温影视灯",
    ModelName: "Lightpanel P1300 Bi",
    image: [
      "image/专业影视灯光/P系列全彩像素影视灯/P1300 Bi/Lightpanel P1300 Bi-1.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P1300 Bi/Lightpanel P1300 Bi-2.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P1300 Bi/Lightpanel P1300 Bi-3.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P1300 Bi/Lightpanel P1300 Bi-4.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P1300 Bi/Lightpanel P1300 Bi-5.png"
    ],
    params: [
      { name: "最大功率", value: "1300W" },
      { name: "LED光源", value: "1216颗灯珠，WW(1300W)+CW(1300W)" },
      { name: "灯光照度", value: "23158Lux@2m/5600K 110°；21850Lux@2m/3200K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "2700K～6500K无级可调色温" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 97" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 103" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "2～25KHz可调" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit / 16bit" },
      { name: "通道模式", value: "3CH /7CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "风扇散热" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP65，防水防尘" },
      { name: "灯体重量", value: "约22.0kg" },
      { name: "体积", value: "880mm×182mm×475mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "P系列全彩像素影视灯",
    id: 43,
    name: "P系列 RGBWW全彩像素影视灯",
    ModelName: "Lightpanel P1300R Hard",
    image: [
      "image/专业影视灯光/P系列全彩像素影视灯/P1300R Hard/Lightpanel P1300R Hard-1.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P1300R Hard/Lightpanel P1300R Hard-2.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P1300R Hard/Lightpanel P1300R Hard-3.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P1300R Hard/Lightpanel P1300R Hard-4.png"
    ],
    params: [
      { name: "最大功率", value: "1300W" },
      { name: "LED光源", value: "3600W（72颗×50W）R/G/B/WW/CW 5合1 LED灯珠" },
      { name: "灯光照度", value: "34924Lux@2m/5600K 25°；27940Lux@2m/3200K 25°" },
      { name: "光束角度", value: "25°/120°" },
      { name: "色温范围", value: "2700K～10000K" },
      { name: "绿/品调节", value: "G/M±1.00" },
      { name: "像素区块", value: "8个像素区域" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "20KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/Bluetooth/Lumenradio CRMX" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP/Art-Net" },
      { name: "调光曲线", value: "4种" },
      { name: "光源特效", value: "12种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP65防水等级" },
      { name: "灯体重量", value: "约246.0kg" },
      { name: "体积", value: "880mm×198mm×475mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "P系列全彩像素影视灯",
    id: 44,
    name: "P系列 双色温影视灯",
    ModelName: "Lightpanel P650 Bi",
    image: [
      "image/专业影视灯光/P系列全彩像素影视灯/P650 Bi/LightPanel P650 Bi-1.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650 Bi/LightPanel P650 Bi-2.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650 Bi/LightPanel P650 Bi-3.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650 Bi/LightPanel P650 Bi-4.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650 Bi/LightPanel P650 Bi-5.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650 Bi/LightPanel P650 Bi-6.png"
    ],
    params: [
      { name: "最大功率", value: "650W" },
      { name: "LED光源", value: "608颗灯珠，WW(650W)+CW(650W)" },
      { name: "灯光照度", value: "12064Lux@2m/5600K 110°；10920Lux@2m/3200K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "2700K～6500K无级可调色温" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 97" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 103" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "2～25KHz可调" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit / 16bit" },
      { name: "通道模式", value: "3CH /7CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "风扇散热" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP65，防水防尘" },
      { name: "灯体重量", value: "约15.0kg" },
      { name: "体积", value: "545mm×198mm×475mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "P系列全彩像素影视灯",
    id: 45,
    name: "P系列 RGBWW全彩像素影视灯",
    ModelName: "Lightpanel P650R Hard",
    image: [
      "image/专业影视灯光/P系列全彩像素影视灯/P650R Hard/P650R Hard-1.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650R Hard/P650R Hard-2.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650R Hard/P650R Hard-3.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650R Hard/P650R Hard-4.png",
      "image/专业影视灯光/P系列全彩像素影视灯/P650R Hard/P650R Hard-5.png"
    ],
    params: [
      { name: "最大功率", value: "650W" },
      { name: "LED光源", value: "1800W（36颗×50W）R/G/B/WW/CW 5合1 LED灯珠" },
      { name: "灯光照度", value: "34924Lux@2m/5600K 25°；27940Lux@2m/3200K 25°" },
      { name: "光束角度", value: "25°/120°" },
      { name: "色温范围", value: "2700K～10000K" },
      { name: "绿/品调节", value: "G/M±1.00" },
      { name: "像素区块", value: "4个像素区域" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "20KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/Bluetooth/Lumenradio CRMX" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP/Art-Net" },
      { name: "调光曲线", value: "4种" },
      { name: "光源特效", value: "12种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP65防水等级" },
      { name: "灯体重量", value: "约16.0kg" },
      { name: "体积", value: "545mm×198mm×475mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "DBi系列聚光灯",
    id: 46,
    name: "SP系列 双色温影视聚光灯",
    ModelName: "SP 200 Bi",
    image: [
      "image/专业影视灯光/DBi系列聚光灯/SP-200Bi/SP-200Bi-1.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-200Bi/SP-200Bi-2.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-200Bi/SP-200Bi-3.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-200Bi/SP-200Bi-4.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-200Bi/SP-200Bi-5.jpg",
      "image/专业影视灯光/DBi系列聚光灯/SP-200Bi/SP-200Bi-6.png"
    ],
    params: [
      { name: "最大功率", value: "200W" },
      { name: "LED光源", value: "WW(200W)+CW(200W)" },
      { name: "灯光照度", value: "22514Lux@2m/15°& 6000K；7474Lux@2m/55°& 6000K" },
      { name: "光束角度", value: "15°～55°" },
      { name: "色温范围", value: "2700K～6500K" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 100" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "2～25KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512 / RDM" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit / 16bit" },
      { name: "调焦模式", value: "手动/电动" },
      { name: "通道模式", value: "手动3CH/7CH；电动5CH9CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "风扇散热/自然冷却" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约9.2 kg" },
      { name: "体积", value: "481mm×324mm×444mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "FC系列全彩聚光灯",
    id: 47,
    name: "FC系列 RGBW全彩影视聚光灯",
    ModelName: "SP 200 FC",
    image: [
      "image/专业影视灯光/FC系列全彩聚光灯/SP-200FC/SP-200FC-1.png",
      "image/专业影视灯光/FC系列全彩聚光灯/SP-200FC/SP-200FC-2.png",
      "image/专业影视灯光/FC系列全彩聚光灯/SP-200FC/SP-200FC-3.png",
      "image/专业影视灯光/FC系列全彩聚光灯/SP-200FC/SP-200FC-4.png"
    ],
    params: [
      { name: "最大功率", value: "200W" },
      { name: "LED光源", value: "200W RGBW 4合1 COB" },
      { name: "灯光照度", value: "15607Lux@2m/15°& 5600K；4772Lux@2m/55°& 6000K" },
      { name: "光束角度", value: "15°～55°" },
      { name: "色温范围", value: "2200K～8500K" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 100" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "2～25KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512 / RDM" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit / 16bit" },
      { name: "调焦模式", value: "手动/电动" },
      { name: "通道模式", value: "手动6CH/10CH；电动8CH/12CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "风扇散热/自然冷却" },
      { name: "工作温度", value: "-20 - 45º C" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "DBi系列聚光灯",
    id: 48,
    name: "SP系列 双色温影视聚光灯",
    ModelName: "SP 350 Bi",
    image: [
      "image/专业影视灯光/DBi系列聚光灯/SP-350Bi/SP-350Bi-1.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-350Bi/SP-350Bi-2.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-350Bi/SP-350Bi-3.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-350Bi/SP-350Bi-4.png"
    ],
    params: [
      { name: "最大功率", value: "350W" },
      { name: "LED光源", value: "WW(350W)+CW(350W)" },
      { name: "灯光照度", value: "46804 Lux@2m/15°& 5600K；11204 Lux@2m/55°& 5600K" },
      { name: "光束角度", value: "15°～55°" },
      { name: "色温范围", value: "2700K～6500K" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 100" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "2～25KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512 / RDM" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit / 16bit" },
      { name: "调焦模式", value: "手动/电动" },
      { name: "通道模式", value: "手动3CH/7CH；电动5CH/9CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "风扇散热" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约9.2 kg" },
      { name: "体积", value: "481mm×324mm×444mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "DBi系列聚光灯",
    id: 49,
    name: "SP系列 单色温影视聚光灯",
    ModelName: "SP 350 D/T",
    image: [
      "image/专业影视灯光/DBi系列聚光灯/SP-350D/SP-350D-1.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-350D/SP-350D-2.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-350D/SP-350D-3.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-350D/SP-350D-4.png",
      "image/专业影视灯光/DBi系列聚光灯/SP-350D/SP-350D-5.png"
    ],
    params: [
      { name: "最大功率", value: "350W" },
      { name: "LED光源", value: "WW(350W) / CW(350W)" },
      { name: "灯光照度", value: "39436 Lux@2m/15°& 3200K；10536 Lux@2m/55°& 3200K" },
      { name: "光束角度", value: "15°～55°" },
      { name: "色温范围", value: "3200K / 5600K" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 100" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "2～25KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512 / RDM" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit / 16bit" },
      { name: "调焦模式", value: "手动/电动" },
      { name: "通道模式", value: "手动2CH；电动4CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "风扇散热" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约9.2 kg" },
      { name: "体积", value: "481mm×324mm×444mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "FC系列全彩聚光灯",
    id: 50,
    name: "FC系列 RGBAL全彩影视聚光灯",
    ModelName: "SP 350 FC",
    image: [
      "image/专业影视灯光/FC系列全彩聚光灯/SP-350FC/SP-350FC-1.png",
      "image/专业影视灯光/FC系列全彩聚光灯/SP-350FC/SP-350FC-2.png",
      "image/专业影视灯光/FC系列全彩聚光灯/SP-350FC/SP-350FC-3.png",
      "image/专业影视灯光/FC系列全彩聚光灯/SP-350FC/SP-350FC-4.png",
      "image/专业影视灯光/FC系列全彩聚光灯/SP-350FC/SP-350FC-5.png",
      "image/专业影视灯光/FC系列全彩聚光灯/SP-350FC/SP-350FC-6.png"
    ],
    params: [
      { name: "最大功率", value: "350W" },
      { name: "LED光源", value: "500W RGBAL 5合1 COB" },
      { name: "灯光照度", value: "46804Lux@2m/15°& 5600K；11204Lux@2m/55°& 6000K" },
      { name: "光束角度", value: "15°～55°" },
      { name: "色温范围", value: "2200K～8500K" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 100" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "2～25KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512 / RDM" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit / 16bit" },
      { name: "调焦模式", value: "手动/电动" },
      { name: "通道模式", value: "手动6CH/10CH；电动8CH/12CH" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512" },
      { name: "调光曲线", value: "4种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "风扇散热/自然冷却" },
      { name: "工作温度", value: "-20 - 45º C" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "ST系列全彩影视灯",
    id: 51,
    name: "ST系列 RGBWW全彩影视柔光灯",
    ModelName: "Lightpanel S1300 ST",
    image: [
      "image/专业影视灯光/ST系列全彩影视灯/S1300 ST/Lightpanel S1300ST-1.png",
      "image/专业影视灯光/ST系列全彩影视灯/S1300 ST/Lightpanel S1300ST-2.png",
      "image/专业影视灯光/ST系列全彩影视灯/S1300 ST/Lightpanel S1300ST-3.png",
      "image/专业影视灯光/ST系列全彩影视灯/S1300 ST/Lightpanel S1300ST-4.png",
      "image/专业影视灯光/ST系列全彩影视灯/S1300 ST/Lightpanel S1300ST-5.png",
      "image/专业影视灯光/ST系列全彩影视灯/S1300 ST/Lightpanel S1300ST-6.png"
    ],
    params: [
      { name: "最大功率", value: "1300W" },
      { name: "LED光源", value: "R+G+B(1800W)、WW(1300W)、CW(1300W)" },
      { name: "灯光照度", value: "6200Lux@2m/5600K 110°；5888Lux@2m/3200K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "2700K～10000K无级可调色温" },
      { name: "绿/品调节", value: "G/M±1.00" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 90" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "20KHz" },
      { name: "控制像素", value: "2个像素" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/Lamp body control" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP" },
      { name: "调光曲线", value: "4种" },
      { name: "光源特效", value: "12种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz；DC 48V" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP65防水等级" },
      { name: "灯体重量", value: "约23.0 kg" },
      { name: "体积", value: "880mm×475mm×182mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "ST系列全彩影视灯",
    id: 52,
    name: "ST系列 RGBWW全彩影视柔光灯",
    ModelName: "Lightpanel S60 ST",
    image: [
      "image/专业影视灯光/ST系列全彩影视灯/S60 ST/Lightpanel S60 ST-1.png",
      "image/专业影视灯光/ST系列全彩影视灯/S60 ST/Lightpanel S60 ST-2.png",
      "image/专业影视灯光/ST系列全彩影视灯/S60 ST/Lightpanel S60 ST-3.png",
      "image/专业影视灯光/ST系列全彩影视灯/S60 ST/Lightpanel S60 ST-4.png",
      "image/专业影视灯光/ST系列全彩影视灯/S60 ST/Lightpanel S60 ST-5.png",
      "image/专业影视灯光/ST系列全彩影视灯/S60 ST/Lightpanel S60 ST-6.png"
    ],
    params: [
      { name: "最大功率", value: "400W" },
      { name: "LED光源", value: "R(468W)、G(468W)、B(468W)、WW(468W)、CW(468W)" },
      { name: "灯光照度", value: "3428Lux@2m/5600K 110°；3328Lux@2m/3200K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "2700K～10000K无级可调色温" },
      { name: "绿/品调节", value: "G/M±1.00" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 90" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "20KHz" },
      { name: "控制像素", value: "2个像素" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/Lamp body control" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP" },
      { name: "调光曲线", value: "4种" },
      { name: "光源特效", value: "12种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz；DC 48V" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP20" },
      { name: "灯体重量", value: "约11.8 kg" },
      { name: "体积", value: "737mm×383mm×191mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "ST系列全彩影视灯",
    id: 53,
    name: "ST系列 RGBWW全彩影视柔光灯",
    ModelName: "Lightpanel S650 ST",
    image: [
      "image/专业影视灯光/ST系列全彩影视灯/S650 ST/Lightpanel S650 ST-1.png",
      "image/专业影视灯光/ST系列全彩影视灯/S650 ST/Lightpanel S650 ST-2.png",
      "image/专业影视灯光/ST系列全彩影视灯/S650 ST/Lightpanel S650 ST-3.png",
      "image/专业影视灯光/ST系列全彩影视灯/S650 ST/Lightpanel S650 ST-4.png",
      "image/专业影视灯光/ST系列全彩影视灯/S650 ST/Lightpanel S650 ST-5.png",
      "image/专业影视灯光/ST系列全彩影视灯/S650 ST/Lightpanel S650 ST-6.png"
    ],
    params: [
      { name: "最大功率", value: "650W" },
      { name: "LED光源", value: "R+G+B(900W)、WW(650W)、CW(650W)" },
      { name: "灯光照度", value: "3940Lux@2m/5600K 110°；3824Lux@2m/3200K 110°" },
      { name: "光束角度", value: "110°" },
      { name: "色温范围", value: "2700K～10000K无级可调色温" },
      { name: "绿/品调节", value: "G/M±1.00" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 90" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "20KHz" },
      { name: "控制像素", value: "2个像素" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/Lamp body control" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit/16bit" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP" },
      { name: "调光曲线", value: "4种" },
      { name: "光源特效", value: "12种" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz；DC 48V" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP65防水等级" },
      { name: "灯体重量", value: "约19.7 kg" },
      { name: "体积", value: "737mm×384mm×182mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "X系列全彩像素影视灯",
    id: 54,
    name: "X系列 RGBWW全彩像素影视灯",
    ModelName: "Lightpanel X21 Hard",
    image: [
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard-1.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard-2.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard-3.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard-4.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard-5.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard-6.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard-7.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard-8.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/X21 Hard双灯.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X21 Hard/x21 Hard三灯.png"
    ],
    params: [
      { name: "最大功率", value: "350W" },
      { name: "LED光源", value: "R(350W)、G(350W)、B(350W)、WW(350W)、CW(350W)" },
      { name: "灯光照度", value: "15366Lux@2m/5600K 25°；14531Lux@2m/3200K 25°" },
      { name: "光束角度", value: "25°/120°" },
      { name: "色温范围", value: "2700K～10000K" },
      { name: "绿/品调节", value: "G/M±1.00" },
      { name: "像素区块", value: "4个像素区域" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "20KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/无线DMX/Wifi-DMX" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit和16bit可切换" },
      { name: "调光曲线", value: "4种" },
      { name: "光源特效", value: "12种" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP/Art-Net" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz；DC 48V" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP65防水等级" },
      { name: "灯体重量", value: "约18.3 kg" },
      { name: "体积", value: "737mm×384mm×180mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "专业影视灯光",
    subCategory: "X系列全彩像素影视灯",
    id: 55,
    name: "X系列 RGBWW全彩像素影视灯",
    ModelName: "Lightpanel X22 Hard",
    image: [
      "image/专业影视灯光/X系列全彩像素影视灯/X22 Hard/X22 Hard-1.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X22 Hard/X22 Hard-2.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X22 Hard/X22 Hard-3.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X22 Hard/X22 Hard-4.png",
      "image/专业影视灯光/X系列全彩像素影视灯/X22 Hard/X22 Hard-5.png"
    ],
    params: [
      { name: "最大功率", value: "650W" },
      { name: "LED光源", value: "R(350W)、G(350W)、B(350W)、WW(650W)、CW(650W)" },
      { name: "灯光照度", value: "34924Lux@2m/5600K 25°；27940Lux@2m/3200K 25°" },
      { name: "光束角度", value: "25°/120°" },
      { name: "色温范围", value: "2700K～10000K" },
      { name: "绿/品调节", value: "G/M±1.00" },
      { name: "像素区块", value: "4个像素区域" },
      { name: "显色指数", value: "CRI≥96" },
      { name: "影视照明一致性指数", value: "TLCI≥ 98" },
      { name: "色彩逼真度", value: "TM-30 Rf 94" },
      { name: "色彩饱和度", value: "TM-30 Rg 102" },
      { name: "颜色质量", value: "CQS ≥96" },
      { name: "LED 寿命", value: "50,000 hours" },
      { name: "调光范围", value: "0～100%" },
      { name: "调光对比度", value: "1000：1" },
      { name: "调光频率", value: "20KHz" },
      { name: "软件升级", value: "通过DMX连接更新软件" },
      { name: "控制模块", value: "DMX512/RDM/无线DMX/Wifi-DMX" },
      { name: "线号连接", value: "DMX IN / DMX OUT" },
      { name: "DMX位数", value: "8bit和16bit可切换" },
      { name: "调光曲线", value: "4种" },
      { name: "光源特效", value: "12种" },
      { name: "数码显示", value: "LCD液晶屏显示" },
      { name: "调光方式", value: "旋钮/DMX512/APP/Art-Net" },
      { name: "供电方式", value: "AC 110～240V，50/60Hz；DC 48V" },
      { name: "电源连接", value: "POWER IN/POWER OUT" },
      { name: "结构与材质", value: "铝合金结构，表面防静电氧化处理" },
      { name: "散热方式", value: "4种散热风扇模式" },
      { name: "工作温度", value: "-20 - 45º C" },
      { name: "防护等级", value: "IP65防水等级" },
      { name: "灯体重量", value: "约18.3 kg" },
      { name: "体积", value: "737mm×384mm×180mm" }
    ],
    description: "描述待填写"
  },
  {
    category: "会议室灯光",
    subCategory: "电动翻转面光灯",
    id: 56,
    name: "会议室电动翻转面光灯",
    ModelName: "LED-HD600",
    image: [
      "image/会议室灯光/1会议室电动翻转平板灯LED-HD600-1.png",
      "image/会议室灯光/1会议室电动翻转平板灯LED-HD600-2.png",
      "image/会议室灯光/1会议室电动翻转平板灯LED-HD600-3.png",
      "image/会议室灯光/1会议室电动翻转平板灯LED-HD600-4.png",
      "image/会议室灯光/1会议室电动翻转平板灯LED-HD600-5.png",
      "image/会议室灯光/1会议室电动翻转平板灯LED-HD600-6.png",
      "image/会议室灯光/1会议室电动翻转平板灯LED-HD600-7.png",
      "image/会议室灯光/1会议室电动翻转平板灯LED-HD600-8.jpg"
    ],
    params: [
      { name: "额定功率", value: "≥200W" },
      { name: "灯珠数量", value: "1080颗高亮LED贴片灯珠" },
      { name: "显色指数", value: "CRI≥96，R9≥90" },
      { name: "影视灯光一致性指数", value: "TLCI≥97" },
      { name: "标准色温", value: "5600K" },
      { name: "光束角度", value: "120°" },
      { name: "翻转角度", value: "0～90°" },
      { name: "翻转模式", value: "电动翻转" },
      { name: "灯珠寿命", value: "约50000小时" },
      { name: "调光范围", value: "0～100% /千分级调光" },
      { name: "光学系统", value: "100%线性调光，无频闪，无噪音" },
      { name: "冷却系统", value: "无风扇自然风冷散热，智能温控恒功率" },
      { name: "操作显示", value: "LED数码显示" },
      { name: "控制协议", value: "DMX512控光协议" },
      { name: "控制方式", value: "主控+DMX控制" },
      { name: "通道数量", value: "2CH单色温" },
      { name: "信号线", value: "XLR-3卡侬头输入，XLR-3卡侬座输出" },
      { name: "电源插座", value: "带锁航空插头（输入/输出）" },
      { name: "外壳材质", value: "钢制+铝合金" },
      { name: "灯体颜色", value: "白色" },
      { name: "安装方式", value: "嵌入式安装" },
      { name: "输入电压", value: "AC110～240V/50～60Hz" },
      { name: "工作温度", value: "-20~50℃" },
      { name: "灯体重量", value: "12.95kg" },
      { name: "灯体尺寸", value: "596mm×596mm×140mm" },
      { name: "开孔尺寸", value: "560mm×510mm" },
      { name: "发光面积", value: "447mm×397mm" },
      { name: "应用场景", value: "视频会议室、录播教室、报告厅、多功能厅等。" }
    ],
    description: "描述待填写"
  },
  {
    category: "会议室灯光",
    subCategory: "高显指柔光顶灯",
    id: 57,
    name: "会议室/录播护眼灯",
    ModelName: "LED-H600",
    image: [
      "image/会议室灯光/2会议室平板灯LED-H600-1.png",
      "image/会议室灯光/2会议室平板灯LED-H600-2.jpg",
      "image/会议室灯光/2会议室平板灯LED-H600-3.png"
    ],
    params: [
      { name: "额定功率", value: "≥120W" },
      { name: "LED光源", value: "168颗3030双芯片180°高亮透镜LED灯珠" },
      { name: "显色指数", value: "CRI≥97" },
      { name: "影视灯光一致性指数", value: "TLCI≥96" },
      { name: "标准色温", value: "5600K" },
      { name: "光照度", value: "2200Lux&1m" },
      { name: "眩光值", value: "UGR≤18" },
      { name: "光束角度", value: "120°" },
      { name: "灯珠寿命", value: "约50000小时" },
      { name: "调光范围", value: "0～100% /千分级调光" },
      { name: "光学系统", value: "100%线性调光，无频闪，无噪音" },
      { name: "冷却系统", value: "无风扇自然风冷散热" },
      { name: "操作显示", value: "LED数码显示" },
      { name: "控制协议", value: "DMX512控光协议" },
      { name: "控制方式", value: "主控+DMX512控制" },
      { name: "通道数量", value: "1CH/3CH" },
      { name: "信号线", value: "XLR-3卡侬头输入，XLR-3卡侬座输出" },
      { name: "电源插座", value: "带锁航空插头（输入/输出）" },
      { name: "外壳材质", value: "铝合金" },
      { name: "灯体颜色", value: "珍珠白色" },
      { name: "安装方式", value: "嵌入式安装" },
      { name: "输入电压", value: "AC110～240V/50～60Hz" },
      { name: "工作温度", value: "-20~60℃" },
      { name: "灯体重量", value: "4.10kg" },
      { name: "灯体尺寸", value: "596mm×596mm×105mm" },
      { name: "开孔尺寸", value: "590mm×590mm" },
      { name: "应用场景", value: "视频会议室、录播教室、报告厅、多功能厅等。" }
    ],
    description: "描述待填写"
  },
  {
    category: "会议室灯光",
    subCategory: "高显指柔光筒灯",
    id: 58,
    name: "会议室高光效筒灯",
    ModelName: "RT-150-24SGGX",
    image: [
      "image/会议室灯光/会议室高光效筒灯RT-150-24SGGX-1.jpg",
      "image/会议室灯光/会议室高光效筒灯RT-150-24SGGX-2.jpg",
      "image/会议室灯光/会议室高光效筒灯RT-150-24SGGX-3.jpg"
    ],
    params: [
      { name: "功率", value: "24W" },
      { name: "尺寸", value: "4寸" },
      { name: "电压", value: "36V" },
      { name: "光源", value: "LED贴片灯珠" },
      { name: "透镜", value: "高光效透镜" },
      { name: "色温", value: "3200~6500K" },
      { name: "显色指数", value: "Ra ≥ 98，R9 ≥ 95" },
      { name: "光束角度", value: "120°" },
      { name: "控制", value: "DMX512恒功率（恒流驱动）" },
      { name: "材质", value: "铝合金" },
      { name: "灯体颜色", value: "白+肤感黑" },
      { name: "灯杯颜色", value: "亮白" },
      { name: "直径/高度", value: "∅ 150mm*H50mm（宽边），∅ 135mm*H50mm（窄边）" },
      { name: "开孔尺寸", value: "∅ 120-135mm（宽边），∅ 120mm（窄边）" },
      { name: "光源尺寸", value: "∅ 83mm" },
      { name: "重量", value: "0.383kg" }
    ],
    description: "描述待填写"
  },
  {
    category: "会议室灯光",
    subCategory: "高显指柔光筒灯",
    id: 59,
    name: "会议室防眩目筒灯",
    ModelName: "RT-175-18SFX",
    image: [
      "image/会议室灯光/会议室防眩目筒灯RT-175-18SFX-1.jpg",
      "image/会议室灯光/会议室防眩目筒灯RT-175-18SFX-2.jpg",
      "image/会议室灯光/会议室防眩目筒灯RT-175-18SFX-3.jpg",
      "image/会议室灯光/会议室防眩目筒灯RT-175-18SFX-4.jpg"
    ],
    params: [
      { name: "功率", value: "18W" },
      { name: "尺寸", value: "5寸" },
      { name: "电压", value: "36V" },
      { name: "光源", value: "LED贴片灯珠" },
      { name: "透镜", value: "防眩透镜" },
      { name: "色温", value: "3200~6500K" },
      { name: "显色指数", value: "Ra ≥ 98，R9 ≥ 97" },
      { name: "光束角度", value: "120°" },
      { name: "控制", value: "DMX512恒功率（恒流驱动）" },
      { name: "材质", value: "铝合金" },
      { name: "灯体颜色", value: "白+黑" },
      { name: "灯杯颜色", value: "亮白" },
      { name: "直径/高度", value: "∅ 175mm*H50mm" },
      { name: "开孔尺寸", value: "∅ 140-165mm" },
      { name: "光源尺寸", value: "∅ 112mm" },
      { name: "重量", value: "0.306kg" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 60,
    name: "ROSCO专业影视抠像漆",
    ModelName: "颜色规格5710#",
    image: [
      "image/控制与配件/影视抠像漆抠像地胶/ROSCO 5710.jpeg"
    ],
    params: [
      { name: "颜色", value: "蓝色（标清）" },
      { name: "容量", value: "3.785L" },
      { name: "VOC含量", value: "＜50g/L" },
      { name: "光泽", value: "哑光" },
      { name: "溶剂", value: "水" },
      { name: "稀释方法", value: "可用水稀释" },
      { name: "干燥时间", value: "＞4小时" },
      { name: "产品使用", value: "搅拌均匀" },
      { name: "膜厚", value: "1/500英寸干膜" },
      { name: "保存时间", value: "≧24个月" },
      { name: "包装材质", value: "铝合金+压铸件" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 61,
    name: "ROSCO专业影视抠像漆",
    ModelName: "颜色规格5750#",
    image: [],
    params: [
      { name: "颜色", value: "蓝色（高清）" },
      { name: "容量", value: "3.785L" },
      { name: "VOC含量", value: "＜50g/L" },
      { name: "光泽", value: "哑光" },
      { name: "溶剂", value: "水" },
      { name: "稀释方法", value: "可用水稀释" },
      { name: "干燥时间", value: "＞4小时" },
      { name: "产品使用", value: "搅拌均匀" },
      { name: "膜厚", value: "1/500英寸干膜" },
      { name: "保存时间", value: "≧24个月" },
      { name: "包装材质", value: "铝合金+压铸件" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 62,
    name: "ROSCO专业影视抠像漆",
    ModelName: "颜色规格5711#",
    image: [
      "image/控制与配件/影视抠像漆抠像地胶/ROSCO 5711.jpeg"
    ],
    params: [
      { name: "颜色", value: "绿色（标清）" },
      { name: "容量", value: "3.785L" },
      { name: "VOC含量", value: "＜50g/L" },
      { name: "光泽", value: "哑光" },
      { name: "溶剂", value: "水" },
      { name: "稀释方法", value: "可用水稀释" },
      { name: "干燥时间", value: "＞4小时" },
      { name: "产品使用", value: "搅拌均匀" },
      { name: "膜厚", value: "1/500英寸干膜" },
      { name: "保存时间", value: "≧24个月" },
      { name: "包装材质", value: "铝合金+压铸件" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 63,
    name: "ROSCO专业影视抠像漆",
    ModelName: "颜色规格5751#",
    image: [
      "image/控制与配件/影视抠像漆抠像地胶/ROSCO 5751.jpg"
    ],
    params: [
      { name: "颜色", value: "绿色（高清）" },
      { name: "容量", value: "3.785L" },
      { name: "VOC含量", value: "＜50g/L" },
      { name: "光泽", value: "哑光" },
      { name: "溶剂", value: "水" },
      { name: "稀释方法", value: "可用水稀释" },
      { name: "干燥时间", value: "＞4小时" },
      { name: "产品使用", value: "搅拌均匀" },
      { name: "膜厚", value: "1/500英寸干膜" },
      { name: "保存时间", value: "≧24个月" },
      { name: "包装材质", value: "铝合金+压铸件" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 64,
    name: "ROSCO专业影视抠像漆",
    ModelName: "颜色规格5735#",
    image: [
      "image/控制与配件/影视抠像漆抠像地胶/ROSCO 5735.jpeg"
    ],
    params: [
      { name: "颜色", value: "白色" },
      { name: "容量", value: "3.785L" },
      { name: "VOC含量", value: "＜50g/L" },
      { name: "光泽", value: "哑光" },
      { name: "溶剂", value: "水" },
      { name: "稀释方法", value: "可用水稀释" },
      { name: "干燥时间", value: "＞4小时" },
      { name: "产品使用", value: "搅拌均匀" },
      { name: "膜厚", value: "1/500英寸干膜" },
      { name: "保存时间", value: "≧24个月" },
      { name: "包装材质", value: "铝合金+压铸件" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 65,
    name: "专业影视抠像漆",
    ModelName: "颜色规格B5730#",
    image: [
      "image/控制与配件/影视抠像漆抠像地胶/国产B5730-1.jpg"
    ],
    params: [
      { name: "颜色", value: "蓝色" },
      { name: "光泽", value: "哑光＜6（60°）" },
      { name: "耐水性", value: "96Hr" },
      { name: "耐碱性", value: "48Hr" },
      { name: "耐擦洗", value: "约1000次" },
      { name: "干燥时间", value: "表干60分钟" },
      { name: "重涂时间", value: "4小时以上（25°C，50%相对湿度）" },
      { name: "理论耗漆量", value: "2遍-5m2/升" },
      { name: "稀释", value: "可用清水稀释" },
      { name: "施工环境", value: "在8°C以上及相对湿度85%以下施工" },
      { name: "贮存期", value: "未开封贮存期为≧24个月，存于0～35°C阴凉干燥处，避免阳光直射。" },
      { name: "包装材质", value: "铝合金+压铸件" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 66,
    name: "专业影视抠像漆",
    ModelName: "颜色规格B5750#",
    image: [
      "image/控制与配件/影视抠像漆抠像地胶/国产B5750-1.jpg"
    ],
    params: [
      { name: "颜色", value: "蓝色" },
      { name: "光泽", value: "哑光＜6（60°）" },
      { name: "耐水性", value: "96Hr" },
      { name: "耐碱性", value: "48Hr" },
      { name: "耐擦洗", value: "约1000次" },
      { name: "干燥时间", value: "表干60分钟" },
      { name: "重涂时间", value: "4小时以上（25°C，50%相对湿度）" },
      { name: "理论耗漆量", value: "2遍-5m2/升" },
      { name: "稀释", value: "可用清水稀释" },
      { name: "施工环境", value: "在8°C以上及相对湿度85%以下施工" },
      { name: "贮存期", value: "未开封贮存期为≧24个月，存于0～35°C阴凉干燥处，避免阳光直射。" },
      { name: "包装材质", value: "铝合金+压铸件" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 67,
    name: "专业影视抠像漆",
    ModelName: "颜色规格G5751#",
    image: [
      "image/控制与配件/影视抠像漆抠像地胶/国产G5751-1.jpg",
      "image/控制与配件/影视抠像漆抠像地胶/国产G5751-2.jpg"
    ],
    params: [
      { name: "颜色", value: "绿色" },
      { name: "光泽", value: "哑光＜6（60°）" },
      { name: "耐水性", value: "96Hr" },
      { name: "耐碱性", value: "48Hr" },
      { name: "耐擦洗", value: "约1000次" },
      { name: "干燥时间", value: "表干60分钟" },
      { name: "重涂时间", value: "4小时以上（25°C，50%相对湿度）" },
      { name: "理论耗漆量", value: "2遍-5m2/升" },
      { name: "稀释", value: "可用清水稀释" },
      { name: "施工环境", value: "在8°C以上及相对湿度85%以下施工" },
      { name: "贮存期", value: "未开封贮存期为≧24个月，存于0～35°C阴凉干燥处，避免阳光直射。" },
      { name: "包装材质", value: "铝合金+压铸件" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "抠像漆/抠像地胶",
    id: 68,
    name: "免漆拼装蓝/绿箱",
    ModelName: "免漆拼装蓝/绿箱",
    image: [
      "image/控制与配件/影视抠像漆抠像地胶/免漆拼装蓝绿箱-1.png",
      "image/控制与配件/影视抠像漆抠像地胶/免漆拼装蓝绿箱-2.jpeg",
      "image/控制与配件/影视抠像漆抠像地胶/免漆拼装蓝绿箱-3.jpg",
      "image/控制与配件/影视抠像漆抠像地胶/免漆拼装蓝绿箱-4.jpg"
    ],
    params: [
      { name: "墙板尺寸", value: "250 * 250 * 17mm（±3mm）" },
      { name: "弧板尺寸", value: "270 * 250 * 17mm（±3mm）" },
      { name: "地板尺寸", value: "250 * 250 * 17mm（±3mm）" },
      { name: "厚度", value: "1块/17mm（±3mm）" },
      { name: "材料", value: "环保TS材料、表面哑光" },
      { name: "地板承重", value: "≧200kg/块" },
      { name: "面积", value: "≧16块/㎡" },
      { name: "颜色", value: "蓝色/绿色" },
      { name: "拼接方式", value: "采用铝合金支架连接" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 69,
    name: "伸缩吊顶灯架",
    ModelName: "Prt-2J-3560",
    image: [
      "image/控制与配件/恒力铰链吊杆/伸缩吊顶灯架/17伸缩吊顶灯架.jpg"
    ],
    params: [
      { name: "材质", value: "钢制+铝合金" },
      { name: "外观", value: "黑色2节伸缩" },
      { name: "高度", value: "350mm～600mm" },
      { name: "底板尺寸", value: "L130mm×W80mm×H4mm" },
      { name: "安装孔", value: "M6×4/M8×4" },
      { name: "承重", value: "≥25kg" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 70,
    name: "T字台吊顶灯架",
    ModelName: "Prt-T058/T118/T168",
    image: [
      "image/控制与配件/恒力铰链吊杆/T字台吊顶灯架/18T字台吊顶灯架.jpg"
    ],
    params: [
      { name: "材质", value: "钢制" },
      { name: "外观", value: "黑色（配银色安全吊环）" },
      { name: "高度", value: "58mm/118mm/168mm" },
      { name: "底板尺寸", value: "L130mm×W80mm×H4mm" },
      { name: "安装孔", value: "M6×4/M8×4" },
      { name: "承重", value: "≥25kg" }
    ],
    description: "描述待填写"
  },
  {
    category: "控制与配件",
    subCategory: "恒力铰链吊杆",
    id: 71,
    name: "拼装式钢结构葡萄架",
    ModelName: "Prt-PTJ03",
    image: [
      "image/控制与配件/恒力铰链吊杆/拼装葡萄架/19拼装葡萄架.jpg"
    ],
    params: [
      { name: "材质", value: "钢制方管" },
      { name: "管径", value: "40×40mm" },
      { name: "颜色", value: "表面做黑色静电喷涂" },
      { name: "尺寸", value: "长度3000mm" },
      { name: "拼接方格", value: "550mm×550mm" },
      { name: "特点", value: "拼装式葡萄架，免现场焊接，避免因焊接产生的火花，安装省心安全。可定制电源输入/输出接口；DMX信号输入/输出接口；" },
      { name: "作用", value: "舞台灯光、演播室灯光挂装使用。" }
    ],
    description: "描述待填写"
  }
];
